"use client"; 

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import SidebarWrapper from "@/components/SidebarWrapper/SidebarWrapper";
import { AuthProvider } from "./auth/AuthProvider/AuthProvider";
import { ConversationProvider } from "@/context/ConversationContext"
import Topbar from "@/components/Header/Header";
import { useSocket } from "@/hooks/useSocket";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  useSocket();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen relative bg-background text-foreground overflow-hidden">
          <SidebarProvider>
            <AuthProvider>
              <SidebarWrapper />
              <div className="flex flex-col relative w-full h-full p-2">
                <Topbar />
                <ConversationProvider>
                  <div className="flex w-full h-full bg-secondary rounded-2xl px-2 mx-2 justify-center items-center">
                    {children}
                  </div>
                </ConversationProvider>
              </div>
            </AuthProvider>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
